name: 'Generate Client'
description: 'Generates a package from a source openapi.yaml file.'
author: 'Oliver Dudgeon'

inputs:
  API_NAME:
    description: 'Name of the API'
    required: true
  API_TARGET_NAME:
    description: 'API name to use for the schemas output target'
    required: true

runs:
  using: 'composite'
  steps:
  # Checkout generator repo
  - uses: actions/checkout@v4
    with:
      repository: InformaticsMatters/openapi-js-client-generator
  - uses: actions/checkout@v4
    with:
      path: "./client"
  # Log the versions for debugging
  - run: |
      echo "Using Node.js version: ${{ env.NODE_JS_VERSION }}"
      echo "Using pnpm version: ${{ env.PNPM_VERSION }}"
    shell: bash
  - uses: actions/setup-node@v4
    with:
      node-version: ${{ env.NODE_JS_VERSION }}
  # Setup pnpm
  - uses: pnpm/action-setup@v4
    with:
      version: ${{ env.PNPM_VERSION }}
  # Get the openapi.yaml file
  - run: |
      echo "Fetching OpenAPI file from: ${GITLAB_API}/${GITLAB_PROJECT}/repository/files/${OPENAPI_PATH}%2F${OPENAPI_FILE}/raw?ref=${CI_COMMIT_TAG}"
      curl -H "Private-Token: ${GITLAB_API_TOKEN}" ${GITLAB_API}/${GITLAB_PROJECT}/repository/files/${OPENAPI_PATH}%2F${OPENAPI_FILE}/raw?ref=${CI_COMMIT_TAG} --output ${OPENAPI_FILE}
      tail ${OPENAPI_FILE}
      cat ${OPENAPI_FILE} | wc -l
    shell: bash
  # Merge the client package.json with the package.json from here, the result is written to package.json.tmp
  - run: jq -s '.[0] * .[1]' ./package.json ./client/package.json | tee package.json.tmp
    shell: bash
  # This temp file is then used to create the new package.json
  # This needs to be done in a separate step as to not read and write to the same file in one step
  - run: mv package.json.tmp package.json
    shell: bash
  # Install dependencies
  - run: pnpm install
    shell: bash
  # Generate the orval config by replacing the placeholders in the orval.config.ts file
  - run: |
      sed -i s/'ORVAL_API_NAME'/'"'${{ inputs.API_NAME }}'"'/ orval.config.ts
      sed -i s/'API_TARGET_NAME'/''${{ inputs.API_TARGET_NAME }}''/ orval.config.ts
      sed -i s/'API_TARGET_NAME'/${{ inputs.API_TARGET_NAME }}/ src/index.ts
      sed -i s/'API_TARGET_NAME'/${{ inputs.API_TARGET_NAME }}/ src/options-mutator.ts
    shell: bash
  # Run orval and tsup to build the client
  - run: |
      pnpm orval
      pnpm build
      ls dist/
      node setup-entrypoints.js
    shell: bash
