name: 'Generate Client'
description: 'Generates a package from a source openapi.yaml file.'
author: 'Oliver Dudgeon'

inputs:
  API_NAME:
    description: 'Name of the API'
    required: true
  API_TARGET_NAME:
    description: 'API name to use for the schemas output target'
    required: true

runs:
  using: 'composite'
  steps:
  # Checkout generator repo
  - uses: actions/checkout@v3
    with:
      repository: InformaticsMatters/openapi-js-client-generator
      branch: main
  - run: ls yarn.lock
    shell: bash
  - uses: actions/checkout@v3
    with:
      path: "./client"
  # We need Node 16
  - uses: actions/setup-node@v2
    with:
      node-version: 16
  # Get the openapi.yaml file
  - run: |
      curl -H "Private-Token: ${GITLAB_API_TOKEN}" ${GITLAB_API}/${GITLAB_PROJECT}/repository/files/${OPENAPI_PATH}%2F${OPENAPI_FILE}/raw?ref=${CI_COMMIT_TAG} --output ${OPENAPI_FILE}
      tail ${OPENAPI_FILE}
      cat ${OPENAPI_FILE} | wc -l
    shell: bash
  - run: npm i --location=global json
    shell: bash
  - run: cat package.json client/package.json | json --deep-merge | tee package.json
    shell: bash
  - run: |
      sed -i s/'ORVAL_API_NAME'/'"'${{ inputs.API_NAME }}'"'/ orval.config.ts
      sed -i s/'API_TARGET_NAME'/''${{ inputs.API_TARGET_NAME }}''/ orval.config.ts
      sed -i s/'API_TARGET_NAME'/${{ inputs.API_TARGET_NAME }}/ src/index.ts
    shell: bash
  - run: yarn
    shell: bash
  - run: |
      yarn orval
      yarn tsup
      ls dist/
      node setup-entrypoints.js
    shell: bash

