name: 'Generate Client'
description: 'Generates a package from a source openapi.yaml file.'
author: 'Oliver Dudgeon'

inputs:
  API_NAME:
    description: 'Name of the API'
    required: true
  API_TARGET_NAME:
    description: 'API name to use for the schemas output target'
    required: true

runs:
  using: 'composite'
  steps:
  # Checkout generator repo
  - uses: actions/checkout@v3
    with:
      repository: InformaticsMatters/openapi-js-client-generator
      branch: main
  - run: cat yarn.lock
    shell: bash
  - uses: actions/checkout@v3
    with:
      path: "./client"
  # We need Node 16
  - uses: actions/setup-node@v2
    with:
      node-version: 16
  - run: yarn cache clean
    shell: bash
  # Get the openapi.yaml file
  - run: |
      curl -H "Private-Token: ${GITLAB_API_TOKEN}" ${GITLAB_API}/${GITLAB_PROJECT}/repository/files/${OPENAPI_PATH}%2F${OPENAPI_FILE}/raw?ref=${CI_COMMIT_TAG} --output ${OPENAPI_FILE}
      tail ${OPENAPI_FILE}
      cat ${OPENAPI_FILE} | wc -l
    shell: bash
  - run: npm i --location=global json
    shell: bash
  - run: cat package.json client/package.json | json --deep-merge | tee package.json
    shell: bash
  - run: cat package.json
    shell: bash
  - run: |
      sed -i s/'ORVAL_API_NAME'/'"'${{ inputs.API_NAME }}'"'/ orval.config.ts
      sed -i s/'API_TARGET_NAME'/''${{ inputs.API_TARGET_NAME }}''/ orval.config.ts
      sed -i s/'API_TARGET_NAME'/${{ inputs.API_TARGET_NAME }}/ src/index.ts
    shell: bash
  - run: yarn add @typescript-eslint/eslint-plugin@5.30.6
    shell: bash
  - run: yarn add axios@0.27.2
    shell: bash
  - run: yarn add eslint@8.20.0
    shell: bash
  - run: yarn add eslint-plugin-prettier@4.2.1
    shell: bash
  - run: yarn add js-yaml@4.1.0
    shell: bash
  - run: yarn add orval@6.9.1
    shell: bash
  - run: yarn add prettier@2.7.1
    shell: bash
  - run: yarn add react-query@3.39.2
    shell: bash
  - run: yarn add tslib@2.4.0
    shell: bash
  - run: yarn add tsup@6.1.3
    shell: bash
  - run: yarn add typescript@4.6.4
    shell: bash
  - run: pwd
    shell: bash
  - run: ls ./node_modules/.bin
    shell: bash
  - run: |
      ./node_modules/.bin/orval
      ./node_modules/.bin/tsup
      ls dist/
      node setup-entrypoints.js
    shell: bash

