// Generated by orval
// API_TARGET_NAME Is replaced with the api name
export * from "./api/api.schemas";

// Request instance and methods to change the baseUrl and auth token
export * from "./custom-instance";
