name: 'Publish Generated Client'
description: 'Publishes a generated NPM package to NPM and GitHub'
author: 'Oliver Dudgeon'

runs:
  using: 'composite'
  steps:
  - name: NPM Config
    run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    env:
      NPM_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
    shell: bash
  - name: Prepare package.json
    run: |
      cat package.json package.release.json | json --deep-merge | tee dist/package.json
    shell: bash
  - name: Prepare Build
    run: |
      cp client/README.md dist/README.md
      cp client/LICENSE dist/LICENSE
      cp -a src dist
      mv dist client
    shell: bash
  - name: Publish
    run: |
      cd client/dist
      git config user.name "${GITHUB_ACTOR}"
      git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      head package.json
      npx -y release-it --npm.skipChecks --ci $CI_COMMIT_TAG
    shell: bash
    env:
      GITHUB_TOKEN : ${{ env.GITHUB_TOKEN }}
